### ISSUE TITLE
The links to DM vial sources are broken

### ISSUE THREAD

**Issue by kaat** [ergohaven/keymap_hub#1]
There are two broken links: https://github.com/ergohaven/keymap_hub, URLs:

https://github.com/ergohaven/vial-qmk/tree/vial/keyboards/handwired/dactyl_manuform/4x6/keymaps/eh
https://github.com/ergohaven/vial-qmk/tree/vial/keyboards/handwired/dactyl_manuform/5x6/keymaps/eh

**Comment by kissetfall** [comment]
Sorry for the late reply, it's has been fixed.
