### ISSUE TITLE
compileable sources for older models you were selling

### ISSUE THREAD

**Issue by petrovs12** [ergohaven/keymap_hub#3]
Hi, I have a dactyl manuform 5x6, purchased in june/july last year, I am 99+ percent certain it is with the promicro controllers, and I am looking to recompile the hex files? How can I do that (seeing its still in warranty). I have sent you an e-mail about it.
the default hex was missing e.g. tap dance. 
I tried to look In the repos, but it seems these files are deLeted, then I found this commit here:
[93273eded05a9b95a12e86a3dada4c5d9542fdc7](https://github.com/ergohaven/vial-qmk/commit/93273eded05a9b95a12e86a3dada4c5d9542fdc7)

which seemed like a good place to start, but there the dm 5x6 is already for the rp2040 controller.  
for rules.mk I could find out the older one in the file history, but the pinout configuration in
https://github.com/ergohaven/vial-qmk/commit/93273eded05a9b95a12e86a3dada4c5d9542fdc7
(i think) didnt compile, so I guess its not correct.

can you please point me to a working config for the promicro based dactyls that work, given you seem to have had them deleted from the repos?

**Comment by petrovs12** [comment]
for reference, before you gave me this link here:
https://github.com/kissetfall/qmk_firmware/tree/master/keyboards/handwired/dactyl_manuform/5x6/keymaps/eh
and i tried to look at it's sister dir in the ergohaven org repo and then do
```
git log --diff-filter=D --summary | grep delete
```

and then try to find the commits that deleted them and try to recover, but grepping the above logs for
handwired\/dactyl_manuform\/5x6\/keymaps\/eh

found nothing

**Comment by kissetfall** [comment]
The fork with all the configs for pro micro was on my personal account and I deleted it after we did a new fork for the organization. Didn't think anyone would ever need it, sorry. I would advise you to just build your own firmware with all the options you need, it's not hard and you can easily check what pins are used.

**Comment by sunaku** [comment]
I have [a modified copy of the sources](https://github.com/sunaku/qmk_firmware/tree/sunaku_dm5x6/keyboards/handwired/dactyl_manuform/5x6_5/keymaps/sunaku/) that came with [my Ergohaven Dactyl Manuform 5x6](https://sunaku.github.io/dactyl-manuform-5x6-keyboard.html) (ProMicro version).  Hope this helps.

**Comment by petrovs12** [comment]
thanks @sunaku this should work!
