### ISSUE TITLE
OSM Key Combo for Shift + RAlt

### ISSUE THREAD

**Issue by itsanonmelody** [ergohaven/keymap_hub#4]
I use the [Seniply](https://stevep99.github.io/seniply/) key layout with [EurKey](https://eurkey.steffen.bruentjen.eu/start.html) key mappings on my Imperial44. I thought it would be nice to have an OSM key combo for Shift + RAlt, so I can type more efficiently when accessing AltGr characters that require the shift key. Currently, I need to do 3-4 strokes in quick succession and switching between the layer key to access the AltGr OSM key and the shift key feels pretty awkward. Would this be possible?

**Comment by kissetfall** [comment]
This should be addressed to qmk-vial repo, please repost your request there.
